export const awardSetup = {
  articleExplorerRequiredNumberOfCategories: 4,
  articleExplorerAwardKind: '6',
  quizMasterRequiredNumberOfCategories: 2,
  quizMasterAwardKind: '7',
  goalCrusherGoalsInARow: 3,
  goalCrusherAwardKind: '8',
  screeningAmbassadorRequiredNumberOfArticles: 2,
  screeningAmbassadorRequiredNumberOfQuizzes: 1,
  screeningAmbassadorRequiredCategory: '30',
  screeningAmbassadorAwardKind: '5',
  superAwareAwardKind: '9',
  serialLearnerAwardKind: '12',
  freshmanDuration: /*10**/60*1000,
  freshmanAwardKind: '16',
};
